engines:
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
      max-len:
        enabled: false
      import/extensions:
        enabled: false
      vars-on-top:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- server/test/