language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g sequelize
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - NODE_ENV=test npm run test:db
script:
  - npm test
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage --compilers js:babel-register